version: '3'
services:
    mssql:
        image: stv707/CHANGE
        restart: always
        container_name: mssql
        environment:
            MSSQL_PID: Evaluation
        volumes:
            - sql:/var/opt/mssql
        ports:
            - "1433:1433"
    
    webapp:
        image: stv707/CHANGE
        container_name: webapp
        environment:
            DBSVR: mssql
        restart: always
        depends_on:
            - mssql
        ports:
            - "80:3000"
volumes:
    sql:
        driver: local
        driver_opts: 
            o: bind
            type: none
            device: /sql2019